{
  "Entries": [
    {
      "RequestUri": "https://vaultname.vault.azure.net/certificates/cert-that-does-not-exist/?api-version=7.5",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Accept": "application/json",
        "Accept-Encoding": "gzip, deflate",
        "User-Agent": "azsdk-python-keyvault-certificates/4.8.0b4 Python/3.10.12 (Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35)"
      },
      "RequestBody": null,
      "StatusCode": 404,
      "ResponseHeaders": {
        "Cache-Control": "no-cache",
        "Content-Length": "336",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Tue, 06 Feb 2024 02:39:51 GMT",
        "Expires": "-1",
        "Pragma": "no-cache",
        "Strict-Transport-Security": "max-age=31536000;includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "x-ms-keyvault-network-info": "conn_type=Ipv4;addr=172.92.159.124;act_addr_fam=InterNetwork;",
        "x-ms-keyvault-rbac-assignment-id": "8a66cbb19e9f472a823418b540a7b3ae",
        "x-ms-keyvault-region": "uksouth",
        "x-ms-keyvault-service-version": "1.9.1272.1"
      },
      "ResponseBody": {
        "error": {
          "code": "CertificateNotFound",
          "message": "A certificate with (name/id) cert-that-does-not-exist was not found in this key vault. If you recently deleted this certificate you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182"
        }
      }
    }
  ],
  "Variables": {}
}
